name: Robottiker
highlighter: true
future: true
tagline: "Documentations"
image: "img/app.png"
repo: "Robottiker"
collections:
  space:
    output: true
  water:
    output: true
  power:
    output: true
