# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Planetary Technology
email: contact@planetary.technology
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: planetarytechnology
github_username: planetarytechnology
github_url: https://github.com/planetarytechnology/planetarytechnology.github.io

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-sass-converter
exclude:
  - Gemfile
  - Gemfile.lock
sass:
  sass_dir: _sass
  style: compressed
navigation:
  - text: Standard
    url: /standard
  - text: Docs
    url: /docs
  - text: Blog
    url: /blog
  - text: Roadmap
    url: /roadmap
  - text: Team
    url: /team
collections:
  digital:
    output: true
  electricity:
    output: true
  heating:
    output: true
  recycling:
    output: true
  structure:
    output: true
  water:
    output: true
